In [1]:
from  snf import compute
import pandas as pd
import os
import glob
import numpy as np
from tqdm import tqdm

In [2]:
interactions = pd.read_csv("../data/SND/drugDiseaseInteractions.txt",sep = "\t", header=None)

In [3]:
unique_drugs = list(set(interactions[0]))
unique_diseases = list(set(interactions[1]))

In [4]:
print(len(unique_diseases),len(unique_drugs))

803 867


In [5]:
ddmatrix = pd.DataFrame(index= unique_drugs, columns=unique_diseases).fillna(0)

In [6]:
for i in interactions.index:
    ddmatrix.loc[interactions.loc[i,0],interactions.loc[i,1]] = 1

In [7]:
print(ddmatrix.sum().sum(), len(interactions))

5685 5685


In [8]:
ddmatrix.to_csv("drug_disease.csv")

In [9]:
drug_folder = "../durgNETs/"
drug_file_paths = glob.glob(os.path.join(drug_folder, '*'))

In [10]:
drug_similarities = []
for j in drug_file_paths:
    sim_data = pd.DataFrame(index= unique_drugs, columns=unique_drugs).fillna(0)
    inter = pd.read_csv(j,sep = "\t", header=None)
    for k in tqdm(inter.index):
        sim_data.loc[inter.loc[k,0],inter.loc[k,1]] = inter.loc[k,2]
        sim_data.loc[inter.loc[k,1],inter.loc[k,0]] = inter.loc[k,2]
    drug_similarities.append(sim_data)
    break

100%|█| 192266/192266 [00:37<00:00, 5174.59i


In [44]:
drug_similarities_np = []
for df in drug_similarities:
    drug_similarities_np.append(df.values)
drug_similarities_np

[array([[0.  , 1.  , 0.9 , ..., 0.85, 0.91, 0.86],
        [1.  , 0.  , 0.99, ..., 0.  , 0.99, 0.99],
        [0.9 , 0.99, 0.  , ..., 0.87, 0.91, 0.84],
        ...,
        [0.85, 0.  , 0.87, ..., 0.  , 0.89, 0.86],
        [0.91, 0.99, 0.91, ..., 0.89, 0.  , 0.92],
        [0.86, 0.99, 0.84, ..., 0.86, 0.92, 0.  ]]),
 array([[0.  , 0.33, 0.33, ..., 0.33, 0.34, 0.33],
        [0.33, 0.  , 0.  , ..., 0.  , 0.31, 0.  ],
        [0.33, 0.  , 0.  , ..., 0.  , 0.31, 0.  ],
        ...,
        [0.33, 0.  , 0.  , ..., 0.  , 0.31, 0.  ],
        [0.34, 0.31, 0.31, ..., 0.31, 0.  , 0.31],
        [0.33, 0.  , 0.  , ..., 0.  , 0.31, 0.  ]]),
 array([[0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  , ..., 0.92, 0.  , 0.  ],
        ...,
        [0.  , 0.  , 0.92, ..., 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ]]),
 array([[0.  , 0.54, 0.54, ..., 0.54,

In [45]:
np.savez("drug_drug_similarity_matrices", *drug_similarities_np)

In [46]:
!ls

drug_disease.csv  drug_drug_similarity_matrices.npz  SNF.ipynb


In [54]:
!pwd

/home2/aswin/drug/Code


In [53]:
npzfile = np.load('drug_drug_similarity_matrices.npz')
drug_drug_sim_matrices = []
for arrname in npzfile:
    drug_drug_sim_matrices.append(npzfile[arrname])
print(len(drug_drug_sim_matrices))
print(drug_drug_sim_matrices[0].shape)

10
(867, 867)


In [57]:
disease_folder = "../diseaseNETs/"
disease_file_paths = glob.glob(os.path.join(disease_folder, '*'))

In [59]:
disease_similarities = []
for j in disease_file_paths:
    sim_data = pd.DataFrame(index= unique_diseases, columns=unique_diseases).fillna(0)
    inter = pd.read_csv(j,sep = "\t", header=None)
    for k in tqdm(inter.index):
        sim_data.loc[inter.loc[k,0],inter.loc[k,1]] = inter.loc[k,2]
        sim_data.loc[inter.loc[k,1],inter.loc[k,0]] = inter.loc[k,2]
    disease_similarities.append(sim_data)  

100%|████████████████████████████████████████████████| 3883/3883 [00:00<00:00, 5229.50it/s]


In [66]:
disease_similarities_np = []
for df in disease_similarities:
    disease_similarities_np.append(df.values)
disease_similarities_np

[array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([[0.  , 0.  , 0.01, ..., 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
        [0.01, 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
        ...,
        [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  , ..., 0.  

In [67]:
np.savez("disease_disease_similarity_matrices", *disease_similarities_np)

In [68]:
npzfile = np.load('disease_disease_similarity_matrices.npz')
disease_disease_sim_matrices = []
for arrname in npzfile:
    disease_disease_sim_matrices.append(npzfile[arrname])
print(len(disease_disease_sim_matrices))
print(disease_disease[0].shape)

14
(803, 803)


In [11]:
# disease_snf = compute.snf(disease_disease_sim_matrices)
disease_snf = np.load("disease_snf14.npy")

In [12]:
# drug_snf = compute.snf(drug_drug_sim_matrices)
drug_snf = np.load("drug_snf19.npy")

In [13]:
interaction_set = set()
for i in interactions.values:
    drugi, diseasei = i[0], i[1]
    interaction_set.add((drugi,diseasei))

In [14]:
from random import randint

non_interaction_set = set()

while len(non_interaction_set) != 10000:
    random_integer = randint(0, len(unique_drugs)-1)
    drug = (unique_drugs[random_integer])
    random_integer = randint(0, len(unique_diseases)-1)
    disease = (unique_diseases[random_integer])
    if (drug,disease) not in interaction_set:
        non_interaction_set.add((drug,disease))

In [15]:
non_interaction_list = list(non_interaction_set)
interaction_list = list(interaction_set)

In [16]:
input_matrix = []
for drug_disease in non_interaction_list:
    drug,disease = drug_disease
    drug_index = (unique_drugs.index(drug))
    disease_index = (unique_diseases.index(disease))
    result = np.concatenate([drug_snf[drug_index], disease_snf[disease_index], np.array([0])])
    input_matrix.append(result)
for drug_disease in interaction_list:
    drug,disease = drug_disease
    drug_index = (unique_drugs.index(drug))
    disease_index = (unique_diseases.index(disease))
    result = np.concatenate([drug_snf[drug_index], disease_snf[disease_index], np.array([1])])
    input_matrix.append(result)
X = np.array(input_matrix)

In [17]:
np.save('dataset_19_14.npy', X)

In [19]:
dataset = np.load('dataset_19_14.npy')
dataset

array([[7.27762103e-04, 1.45536870e-03, 1.40500976e-03, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [7.34034630e-04, 1.47430922e-03, 1.42314149e-03, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.36208382e-04, 1.39355364e-03, 1.34784706e-03, ...,
        0.00000000e+00, 1.97119111e-04, 0.00000000e+00],
       ...,
       [7.47166469e-04, 1.31171746e-03, 1.26755293e-03, ...,
        0.00000000e+00, 7.71159481e-06, 1.00000000e+00],
       [5.36208382e-04, 1.39355364e-03, 1.34784706e-03, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [7.34175571e-04, 1.47461382e-03, 1.42311928e-03, ...,
        0.00000000e+00, 3.61394077e-04, 1.00000000e+00]])

In [121]:
unique_drugs

['DB00626',
 'DB00737',
 'DB01129',
 'DB00178',
 'DB00811',
 'DB01591',
 'DB00987',
 'DB01044',
 'DB00503',
 'DB00661',
 'DB01364',
 'DB00014',
 'DB00072',
 'DB01208',
 'DB00302',
 'DB00979',
 'DB00755',
 'DB00332',
 'DB06176',
 'DB01357',
 'DB09128',
 'DB00295',
 'DB01275',
 'DB00266',
 'DB01095',
 'DB00831',
 'DB00996',
 'DB01188',
 'DB09096',
 'DB00080',
 'DB00988',
 'DB06820',
 'DB01246',
 'DB01400',
 'DB06694',
 'DB01197',
 'DB04930',
 'DB09324',
 'DB00819',
 'DB00137',
 'DB05578',
 'DB00571',
 'DB00195',
 'DB00573',
 'DB01377',
 'DB09060',
 'DB08819',
 'DB00884',
 'DB00253',
 'DB01047',
 'DB01112',
 'DB06824',
 'DB00052',
 'DB01320',
 'DB00973',
 'DB00223',
 'DB00435',
 'DB00852',
 'DB00310',
 'DB00214',
 'DB01121',
 'DB01110',
 'DB01607',
 'DB00227',
 'DB00564',
 'DB01091',
 'DB00427',
 'DB09543',
 'DB00319',
 'DB04843',
 'DB08877',
 'DB00601',
 'DB00259',
 'DB01147',
 'DB06791',
 'DB01061',
 'DB00719',
 'DB01015',
 'DB00177',
 'DB01165',
 'DB09350',
 'DB00285',
 'DB06769',
 'DB