In [1]:
import numpy as np
import pandas as pd

In [2]:
# load the matrix from the text file
# drug_simmat = np.loadtxt('../MBiRW/Datasets/DrugSimMat')
# print(drug_simmat)

In [3]:
# load the matrix from the text file
# drug_names = np.genfromtxt('../MBiRW/Datasets/DrugsName', dtype='str')
# print(drug_names, drug_names.shape)

In [35]:
drug_data = pd.read_csv("../../data/SND/drug_snf19.csv", index_col=0 )
drug_simmat = drug_data.values

In [8]:
drug_names = list(drug_data.index)

In [12]:
import json

# load the dictionary from the file
with open('../data/gene_dict_drug.json', 'r') as file:
    gene_dict_drug = json.load(file)
    
# print(gene_dict_drug)

In [13]:
count = 0 
for i in drug_names:
    if i in gene_dict_drug:
        count+=1
print(count)

705


In [14]:
print(len(drug_names))

867


In [15]:
disease_data = pd.read_csv("../../data/SND/disease_snf14.csv", index_col=0 )

In [24]:
### Run if the dataset is SND only
with open('../../data/SND/SNF_diseases_matched.json', 'r') as file:
    snf_disease = json.load(file)


# Loop through DataFrame's index, and set new index based on dictionary or random number
for index in disease_data.index:
    if index in snf_disease:
        disease_data = disease_data.rename(index={index: snf_disease[index]})
    else:
        disease_data = disease_data.rename(index={index: index})

disease_data

C0000810  C0001144  C0001206  C0001261  C0001403  C0001627  \
C0000810       1.5  0.000000  0.000000       0.0  0.000000  0.000000   
D000152        0.0  1.051848  0.001223       0.0  0.007788  0.001184   
D000172        0.0  0.001223  1.033249       0.0  0.001045  0.002525   
D000196        0.0  0.000000  0.000000       1.5  0.000000  0.000000   
D000224        0.0  0.007788  0.001045       0.0  1.161785  0.000262   
...            ...       ...       ...       ...       ...       ...   
C3873567       0.0  0.000000  0.000000       0.0  0.000000  0.000000   
C3875286       0.0  0.000000  0.000000       0.0  0.000000  0.000000   
C3875321       0.0  0.000000  0.000000       0.0  0.000000  0.000000   
C3898069       0.0  0.000419  0.000212       0.0  0.000731  0.000000   
C4038730       0.0  0.000249  0.000149       0.0  0.000872  0.000000   

          C0001957  C0002395  C0002726  C0002874  ...  C3495559  C3495917  \
C0000810  0.000000       0.0  0.000000  0.000000  ...  0.000000       0.0   
D000152   0.000341       0.0  0.002557  0.002376  ...  0.003173       0.0   
D000172   0.003249       0.0  0.001771  0.001395  ...  0.001476       0.0   
D000196   0.000000       0.0  0.000000  0.000000  ...  0.000000       0.0   
D000224   0.000239       0.0  0.001071  0.001439  ...  0.001150       0.0   
...            ...       ...       ...       ...  ...       ...       ...   
C3873567  0.000000       0.0  0.000000  0.000000  ...  0.000000       0.0   
C3875286  0.000000       0.0  0.000000  0.000000  ...  0.000000       0.0   
C3875321  0.000000       0.0  0.000000  0.000017  ...  0.000572       0.0   
C3898069  0.000000       0.0  0.001993  0.000757  ...  0.000520       0.0   
C4038730  0.000000       0.0  0.001788  0.000233  ...  0.000413       0.0   

          C3665800  C3665869  C3698411  C3873567  C3875286  C3875321  \
C0000810  0.000000  0.000000  0.000000       0.0       0.0  0.000000   
D000152   0.000726  0.000875  0.000039       0.0       0.0  0.000000   
D000172   0.001770  0.000583  0.000270       0.0       0.0  0.000000   
D000196   0.000000  0.000000  0.000000       0.0       0.0  0.000000   
D000224   0.000217  0.000844  0.000028       0.0       0.0  0.000000   
...            ...       ...       ...       ...       ...       ...   
C3873567  0.000000  0.000000  0.000000       1.5       0.0  0.000000   
C3875286  0.000000  0.000000  0.000000       0.0       1.5  0.000000   
C3875321  0.000000  0.000000  0.000000       0.0       0.0  1.112746   
C3898069  0.000610  0.001718  0.000055       0.0       0.0  0.000000   
C4038730  0.000414  0.000719  0.000034       0.0       0.0  0.000000   

          C3898069  C4038730  
C0000810  0.000000  0.000000  
D000152   0.000419  0.000249  
D000172   0.000212  0.000149  
D000196   0.000000  0.000000  
D000224   0.000731  0.000872  
...            ...       ...  
C3873567  0.000000  0.000000  
C3875286  0.000000  0.000000  
C3875321  0.000000  0.000000  
C3898069  1.061021  0.001434  
C4038730  0.001434  1.097603  

[803 rows x 803 columns]

In [25]:
disease_names = list(disease_data.index)

In [26]:
# load the dictionary from the file
with open('../data/gene_dict_disease.json', 'r') as file:
    gene_dict_disease = json.load(file)

In [27]:
count = 0 
for i in disease_names:
    if i in gene_dict_disease:
        count+=1
print(count)

436


In [28]:
len(disease_names)

803

In [29]:
disease_present = []
for disease in disease_names:
    if disease in gene_dict_disease and gene_dict_disease[disease] != []:
        disease_present.append(disease)
drug_present = []
for drug in drug_names:
    if drug in gene_dict_drug and gene_dict_drug[drug] != []:
        drug_present.append(drug)

In [31]:
len(disease_present) , len(drug_present)

(436, 705)

In [36]:
new_drug_simmat = np.zeros((len(drug_present),len(drug_present)))
indices = np.zeros(len(drug_present), dtype = int)
cur = 0
for i, drug in enumerate(drug_names):
    if(drug in drug_present):
        indices[cur] = i
        cur+=1
        
cur = 0
for i in indices:
    new_drug_simmat[cur] = drug_simmat[i, indices]
    cur+=1

print(new_drug_simmat,new_drug_simmat.shape)
drug_indices = indices

[[0.54516043 0.00148496 0.00137755 ... 0.0013777  0.00128037 0.00128037]
 [0.00148496 0.54499035 0.00137999 ... 0.00137895 0.00127984 0.00127984]
 [0.00137755 0.00137999 0.5401678  ... 0.00153366 0.00146522 0.00146522]
 ...
 [0.0013777  0.00137895 0.00153366 ... 0.54019724 0.00146573 0.00146573]
 [0.00128037 0.00127984 0.00146522 ... 0.00146573 0.54655882 0.00157648]
 [0.00128037 0.00127984 0.00146522 ... 0.00146573 0.00157648 0.54655882]] (705, 705)


In [37]:
disease_simmat = disease_data.values
print(disease_simmat, disease_simmat.shape)

[[1.50000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.05184812e+00 1.22287099e-03 ... 0.00000000e+00
  4.19172193e-04 2.49010903e-04]
 [0.00000000e+00 1.22287099e-03 1.03324923e+00 ... 0.00000000e+00
  2.12190984e-04 1.49265063e-04]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.11274592e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 4.19172193e-04 2.12190984e-04 ... 0.00000000e+00
  1.06102132e+00 1.43396885e-03]
 [0.00000000e+00 2.49010903e-04 1.49265063e-04 ... 0.00000000e+00
  1.43396885e-03 1.09760313e+00]] (803, 803)


In [38]:
new_disease_simmat = np.zeros((len(disease_present),len(disease_present)))
indices = np.zeros(len(disease_present), dtype = int)
cur = 0
for i, disease in enumerate(disease_names):
    if(disease in disease_present):
        indices[cur] = i
        cur+=1
        
cur = 0
for i in indices:
    new_disease_simmat[cur] = disease_simmat[i, indices]
    cur+=1

print(new_disease_simmat,new_disease_simmat.shape)
disease_indices = indices

[[1.05184812e+00 1.22287099e-03 0.00000000e+00 ... 3.51629508e-02
  8.71656340e-04 3.17308048e-03]
 [1.22287099e-03 1.03324923e+00 0.00000000e+00 ... 2.78197211e-03
  3.25092231e-04 1.47645285e-03]
 [0.00000000e+00 0.00000000e+00 1.50000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [3.51629508e-02 2.78197211e-03 0.00000000e+00 ... 1.18400155e+00
  7.83059518e-04 2.60499569e-03]
 [8.71656340e-04 3.25092231e-04 0.00000000e+00 ... 7.83059518e-04
  1.09214330e+00 1.70009289e-03]
 [3.17308048e-03 1.47645285e-03 0.00000000e+00 ... 2.60499569e-03
  1.70009289e-03 9.91719565e-01]] (436, 436)


In [39]:
drug_df = pd.DataFrame(new_drug_simmat, index = drug_names[drug_indices], columns= drug_names[drug_indices])
drug_df

DB00002   DB00005   DB00007   DB00008   DB00009   DB00014   DB00016  \
DB00002  0.545160  0.001485  0.001378  0.001450  0.001455  0.001167  0.001378   
DB00005  0.001485  0.544990  0.001380  0.001465  0.001454  0.001214  0.001375   
DB00007  0.001378  0.001380  0.540168  0.001372  0.001379  0.001112  0.001531   
DB00008  0.001450  0.001465  0.001372  0.546199  0.001456  0.001345  0.001375   
DB00009  0.001455  0.001454  0.001379  0.001456  0.544980  0.001173  0.001378   
...           ...       ...       ...       ...       ...       ...       ...   
DB09082  0.001377  0.001380  0.001534  0.001372  0.001379  0.001112  0.001531   
DB09128  0.001325  0.001329  0.001472  0.001320  0.001327  0.001074  0.001467   
DB09272  0.001378  0.001379  0.001534  0.001373  0.001379  0.001111  0.001533   
DB09302  0.001280  0.001280  0.001465  0.001273  0.001280  0.000963  0.001469   
DB09303  0.001280  0.001280  0.001465  0.001273  0.001280  0.000963  0.001469   

          DB00017   DB00026   DB00030  ...   DB09054   DB09074   DB09075  \
DB00002  0.001376  0.001379  0.001377  ...  0.001376  0.001377  0.001376   
DB00005  0.001375  0.001379  0.001378  ...  0.001382  0.001382  0.001382   
DB00007  0.001531  0.001534  0.001533  ...  0.001534  0.001534  0.001534   
DB00008  0.001373  0.001373  0.001373  ...  0.001371  0.001371  0.001371   
DB00009  0.001378  0.001379  0.001379  ...  0.001379  0.001379  0.001379   
...           ...       ...       ...  ...       ...       ...       ...   
DB09082  0.001531  0.001533  0.001533  ...  0.001535  0.001535  0.001535   
DB09128  0.001467  0.001471  0.001471  ...  0.001474  0.001474  0.001474   
DB09272  0.001533  0.001534  0.001534  ...  0.001533  0.001533  0.001533   
DB09302  0.001469  0.001466  0.001466  ...  0.001464  0.001464  0.001464   
DB09303  0.001469  0.001466  0.001466  ...  0.001464  0.001464  0.001464   

          DB09078   DB09079   DB09082   DB09128   DB09272   DB09302   DB09303  
DB00002  0.001328  0.001326  0.001377  0.001325  0.001378  0.001280  0.001280  
DB00005  0.001333  0.001331  0.001380  0.001329  0.001379  0.001280  0.001280  
DB00007  0.001477  0.001474  0.001534  0.001472  0.001534  0.001465  0.001465  
DB00008  0.001323  0.001321  0.001372  0.001320  0.001373  0.001273  0.001273  
DB00009  0.001330  0.001329  0.001379  0.001327  0.001379  0.001280  0.001280  
...           ...       ...       ...       ...       ...       ...       ...  
DB09082  0.001477  0.001475  0.540152  0.001473  0.001533  0.001465  0.001465  
DB09128  0.001564  0.001566  0.001473  0.537158  0.001472  0.001409  0.001409  
DB09272  0.001475  0.001473  0.001533  0.001472  0.540197  0.001466  0.001466  
DB09302  0.001413  0.001411  0.001465  0.001409  0.001466  0.546559  0.001576  
DB09303  0.001413  0.001411  0.001465  0.001409  0.001466  0.001576  0.546559  

[705 rows x 705 columns]

In [40]:
disease_df = pd.DataFrame(new_disease_simmat, index = np.array(disease_names)[disease_indices], columns= np.array(disease_names)[disease_indices])
disease_df

D000152   D000172  D000196   D000224   D000312   D000430  D000544  \
D000152  1.051848  0.001223      0.0  0.007788  0.001184  0.000341      0.0   
D000172  0.001223  1.033249      0.0  0.001045  0.002525  0.003249      0.0   
D000196  0.000000  0.000000      1.5  0.000000  0.000000  0.000000      0.0   
D000224  0.007788  0.001045      0.0  1.161785  0.000262  0.000239      0.0   
D000312  0.001184  0.002525      0.0  0.000262  1.157996  0.000149      0.0   
...           ...       ...      ...       ...       ...       ...      ...   
D006192  0.000000  0.000000      0.0  0.000000  0.000000  0.000000      0.0   
D010149  0.000000  0.000000      0.0  0.000000  0.000000  0.000000      0.0   
D056587  0.035163  0.002782      0.0  0.004883  0.000883  0.000422      0.0   
D065631  0.000872  0.000325      0.0  0.000358  0.000119  0.000163      0.0   
D001171  0.003173  0.001476      0.0  0.001150  0.002012  0.001378      0.0   

          D000686   D000741   D017086  ...   D011657   D001170  D011472  \
D000152  0.002557  0.002376  0.000246  ...  0.000062  0.002177      0.0   
D000172  0.001771  0.001395  0.001247  ...  0.000093  0.001813      0.0   
D000196  0.000000  0.000000  0.000000  ...  0.000000  0.000000      0.0   
D000224  0.001071  0.001439  0.000134  ...  0.000096  0.001464      0.0   
D000312  0.001202  0.001160  0.000148  ...  0.000000  0.001618      0.0   
...           ...       ...       ...  ...       ...       ...      ...   
D006192  0.000000  0.000000  0.000000  ...  0.000000  0.000000      0.0   
D010149  0.000000  0.000000  0.000000  ...  0.000000  0.000000      0.0   
D056587  0.001479  0.002415  0.000277  ...  0.000000  0.002066      0.0   
D065631  0.002230  0.001410  0.000156  ...  0.000933  0.001965      0.0   
D001171  0.001533  0.001427  0.000727  ...  0.000496  0.001775      0.0   

          D011470  D054218  D006192  D010149   D056587   D065631   D001171  
D000152  0.000021      0.0      0.0      0.0  0.035163  0.000872  0.003173  
D000172  0.000022      0.0      0.0      0.0  0.002782  0.000325  0.001476  
D000196  0.000000      0.0      0.0      0.0  0.000000  0.000000  0.000000  
D000224  0.000008      0.0      0.0      0.0  0.004883  0.000358  0.001150  
D000312  0.000000      0.0      0.0      0.0  0.000883  0.000119  0.002012  
...           ...      ...      ...      ...       ...       ...       ...  
D006192  0.000000      0.0      1.5      0.0  0.000000  0.000000  0.000000  
D010149  0.000000      0.0      0.0      1.5  0.000000  0.000000  0.000000  
D056587  0.000000      0.0      0.0      0.0  1.184002  0.000783  0.002605  
D065631  0.000032      0.0      0.0      0.0  0.000783  1.092143  0.001700  
D001171  0.000071      0.0      0.0      0.0  0.002605  0.001700  0.991720  

[436 rows x 436 columns]

In [41]:
drug_df.to_csv('../../data/processed_drug_simmat_SNF19.csv')
disease_df.to_csv('../../data/processed_disease_simmat_SNF14.csv')